### ISSUE TITLE
Ember.View still in API documentation

### ISSUE THREAD

**Issue by vvscode** [emberjs/website#2504] opened 2016-03-18 09:16 UTC
Documentation  for Ember.View still in documentation. But it not in API ( 2.2 / 2.4 and 2.x in common )

http://emberjs.com/api/classes/Ember.View.html

Fix please

**Comment by acorncom** [comment] 2016-03-18 15:16
@vvscode Good catch.  We're working on it over here (#2452), but it's going to take some work.  If you've got some spare time, I know Todd would be happy to have a hand :smile: 

I'll close this issue as a duplicate of the other one.

**Closed by acorncom** 2016-03-18 15:16 UTC
