### ISSUE TITLE
Who's Using Ember.js? slider - logos jump down when changing between last and first slide

### ISSUE THREAD

**Issue by thisFunction** [emberjs/website#3346] opened 2018-05-17 18:59 UTC
When changing between last and first slide the logos jump down.

[Click here to see video](https://photos.google.com/share/AF1QipOTVGDHXNbC_IXDIA8L876swhUvmZKdQTvcV9Heav9GxvCZIs50UJS5K-s59faNRw?key=WTQ4VE9YWEtBaGI4bmJmOVFmVXdYZWNXaHBFWTRR)

**Comment by MelSumner** [comment] 2018-05-19 23:48
This is a duplicate of https://github.com/emberjs/website/issues/3134 - thank you! :+1:

**Closed by MelSumner** 2018-05-19 23:48 UTC
