### ISSUE TITLE
Is search on the Ember website / guide broken?

### ISSUE THREAD

**Issue by camoore1979** [emberjs/website#2359] opened 2015-09-04 17:14 UTC
I'm trying to use the search bar on the Emberjs.com website for the guide, and it is broken.

The url is:  http://guides.emberjs.com/v1.13.0/#stq=array&stp=1

Here's the error in the console.log:
![image](https://cloud.githubusercontent.com/assets/4583280/9689863/d56ab588-5306-11e5-896f-8d33bc66a998.png)

**Comment by acorncom** [comment] 2015-10-16 02:34
Yes, it was, it should be fixed now (though only for newer docs sadly :-/)

**Comment by acorncom** [comment] 2015-12-17 22:49
Sadly, due to the way our current infrastructure is setup, we may not be able to get this fixed for older 1.13 guides.  This should be resolved in the newer guides, so closing it now.  Please re-open if you're still seeing issues ...

**Closed by acorncom** 2015-12-17 22:49 UTC

**Comment by samchrisinger** [comment] 2016-02-02 21:17
Getting: 
```
Uncaught TypeError: Cannot read property 'query' of undefined
d @ swiftype_nocode-d8273559be65c04593eb2a85dc0df637.js:formatted:6994
c @ swiftype_nocode-d8273559be65c04593eb2a85dc0df637.js:formatted:891
h.fireWith @ swiftype_nocode-d8273559be65c04593eb2a85dc0df637.js:formatted:948
r @ swiftype_nocode-d8273559be65c04593eb2a85dc0df637.js:formatted:3885
n.onload.n.onreadystatechange @ swiftype_nocode-d8273559be65c04593eb2a85dc0df637.js:formatted:4082
```
On the latest docs: https://guides.emberjs.com/v2.3.0/#stq=class

**Comment by acorncom** [comment] 2016-02-03 15:36
Confirmed, we've got an issue open about it: https://github.com/emberjs/guides/issues/1183
