### ISSUE TITLE
Add spellchecker to the website build system

### ISSUE THREAD

**Issue by acorncom** [emberjs/website#2488] opened 2016-03-04 22:22 UTC
We have occasional misspellings slip through on the Ember website.  It would be nice to have a spell checker build step setup like we have for the guides to help alleviate this issue in the future.  Please reference https://github.com/emberjs/guides/pull/998 for more details about how it was setup there ...

**Comment by green-arrow** [comment] 2016-03-23 17:28
@acorncom - I have a WIP branch ([comparison here](https://github.com/emberjs/website/compare/master...green-arrow:spell-check?expand=1)), with spell check working. The problem is, there are a **lot** of spelling errors. There are simply a lot of unique words, names in blog posts, and places where github / twitter names are used without being enclosed in an anchor tag.

I figured I'd post the WIP to try and see if anyone has any suggestions for speeding up this process of fixing the errors.

**Comment by acorncom** [comment] 2016-03-23 19:53
Hmm, not sure I've got a ton of suggestions there.  We could continue teaching it various github / twitter names (which might help with some exceptions).  If there anyway to do a filter on what files are checked?    My inclination would be to only check blog posts for 2016 (and possibly 2015 if you want to) so that we catch new things.  If we could blacklist all other pages and slowly turn off the blacklisting in chunks we might be able to get this in without it being a huge task to start with ...

Thoughts?

**Comment by green-arrow** [comment] 2016-03-24 13:22
Even adding valid exceptions to the exceptions file would take significant effort, as there appear to be well over a hundred "mis-spellings".

There definitely is a way to ignore older blog posts, I will take a look at that today and see how much that resolves. I think one of the big things to keep in mind moving forward will be to always wrap github / twitter user names in a link, as I can blanket ignore all links with a specific URL.

**Comment by green-arrow** [comment] 2016-03-24 14:15
*Update:* Restricting this to only blog posts from 2015 onward significantly reduced the number of issues. However, it seems that `middleman-spellcheck` runs its check after build on the `.html` files. There is an issue with this because of how headers are parsed from markdown -> HTML.

When there are two headers in a row, they are rendered side-by-side in HTML, and it appears that causes the text to appear side-by-side with no space, causing random mis-spellings with headers next to each other. I'm not familiar enough with `middleman-spellcheck` to know how to fix that.

**Comment by jessica-jordan** [comment] 2018-10-02 13:16
Are you alright with closing this issue and addressing this in another one with a bit more description? Maybe a first-time contributor could pick it up during Hacktoberfest @acorncom

**Comment by jessica-jordan** [comment] 2018-10-02 13:35
I transferred this over to #3597 - feel free to reopen this issue or mention if something is missing in the new one!

**Closed by jessica-jordan** 2018-10-02 13:35 UTC
Labels: good first issue
