### ISSUE TITLE
Suggestion: better explanation of Radio button support in API docs

### ISSUE THREAD

**Issue by plaughton** [emberjs/website#2574] opened 2016-05-02 16:28 UTC
I have been working on ember for a few months, and have just spent a long weekend trying to make a radio input checked work in ember. 

I could get {{input type="radio" value=model.var1}} working nicely except that it would not show an existing value i.e. I could not get checked="checked" or similar to work. 

I asked a couple of experienced ember dev's and they felt that this has not been included in ember because checkbox can be configured (with a computed property) to emulate the checkbox. I understand that this is probably a good idea as it ensures that a constraint sits in the logic of the program.

Given that radio buttons are such a common html element and that input type="radio" mostly works it would be really useful for a beginner to have seen something referring to radio buttons in the docs (perhaps in http://emberjs.com/api/classes/Ember.Templates.helpers.html#method_input). I realise that this is implicit in that there is no mention of radio support for input, but I think seeing a comment in the official docs is helpful, and will also help the docs index for google searches in this area. 

I would also suggest that it may be useful to mention that checkbox should be used with computed properties instead, if this is indeed the strategy. Would work well as an example in the checkbox section of the API docs.

**Comment by locks** [comment] 2016-05-03 00:15
Hi @plaughton, thank you for your feedback! This isn't quite the right repository to open this issue on, but since it's a bit confusing let's explore the idea before potentially redirecting.

Radio buttons are confusing in of themselves, so coupling them with Ember doesn't help, right ;) Since we already have a guide on [input helpers](https://guides.emberjs.com/v2.5.0/templates/input-helpers/), my first suggestion would be to address the radio button there, in a way that flows with the rest of the Guides.

Do you have a reproduction, for example using [Ember Twiddle](https://ember-twiddle.com) with the suggestions from the experienced Ember developers?

**Comment by iezer** [comment] 2016-06-26 20:15
👍  on this issue. I opened in a ticket in the guides repo https://github.com/emberjs/guides/issues/1535 . I suggest closing this ticket in favor of that one @plaughton  .

**Comment by mixonic** [comment] 2016-06-27 19:29
Closing in favor of https://github.com/emberjs/guides/issues/1535

**Closed by mixonic** 2016-06-27 19:29 UTC
