### ISSUE TITLE
Update Examples on the Homepage to use ES6 + modules.

### ISSUE THREAD

**Issue by martndemus** [emberjs/website#2713] opened 2016-11-03 16:29 UTC
I just had a case we're I showed someone new to Ember the frontpage.

One of the first examples he looked at was:
```
App.GravatarImageComponent = Ember.Component.extend({
  size: 200,
  email: '',

  gravatarUrl: Ember.computed('email', 'size', function() {
    var email = this.get('email').toLowerCase(),
        size = this.get('size');

    return 'http://www.gravatar.com/avatar/' + md5(email) + '?s=' + size;
  })
});
```

His first reaction was: "That's horrible, it looks like Backbone!".
So I asked him what part did make it feel like Backbone. He answered that `App.GravatarImageComponent` did.

Therefore I think we should make it an issue to update the homepage of emberjs.com as quickly as possible.

**Comment by locks** [comment] 2016-11-03 16:31
Duplicate of https://github.com/emberjs/website/issues/2369.

**Closed by locks** 2016-11-03 16:31 UTC
